### ISSUE TITLE
List to Postgres fails with "AttributeError: 'DiGraph object has no attribute 'edge'"

### ISSUE THREAD

**Issue by CHelfgott** [blaze/odo#588]
Running this with the latest version pulled off of Github, and Python 3.5.  (I was using odo 0.5.0, and was getting an error in a very similar location before I upgraded.)

Here's the full error logs:  

  File "./flatfile_parser.py", line 629, in <module>
    main()
  File "./flatfile_parser.py", line 614, in main
    odo(temp_table, pg_conn_str + "::" + table_name, dshape = dshape_str)
  File "/usr/local/lib/python3.5/dist-packages/odo/odo.py", line 91, in odo
    return into(target, source, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 143, in into_string
    return into(a, b, dshape=dshape, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 131, in into_object
    return append(target, source, dshape=dshape, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/backends/sql.py", line 527, in append_anything_to_sql_Table
    return append(t, convert(Iterator, o, **kwargs), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/core.py", line 83, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/core.py", line 100, in _transform
    ooc_types=ooc_types)
  File "/usr/local/lib/python3.5/dist-packages/odo/core.py", line 172, in path
    edge = graph.edge
AttributeError: 'DiGraph' object has no attribute 'edge'

**Comment by CHelfgott** [comment]
Apparently line 1.72 only works with networkx v1.9; networkx is currently at 2.0.

**Comment by mythnc** [comment]
This issue is related to #579

**Comment by asokadiggs** [comment]
I'm encountering this error as well.  Doing some additional reading, I found this Migration Guide for migrating from networkx 1.x to networkx 2.x:
https://networkx.github.io/documentation/latest/release/migration_guide_from_1.x_to_2.0.html

The key bit for this is quoted here:
"Replace any use of G.edge with G.adj. The Graph attribute edge has been removed. The attribute G.adj is G.edge in v1 and will work with both versions."

I manually edited core.py in my local install of odo and the error didn't appear (though I'm still trying to get my first succerssful write to the db using odo, so I can't confirm this single edit fully fixes this error).

**Comment by elakhna** [comment]
Any update here? I'm still getting this.

**Comment by dhirschfeld** [comment]
You need to downgrade your `networkx` to `<2.0` until this is fixed
