### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'edge'  - when trying to use odo

### ISSUE THREAD

**Issue by bwhitby** [blaze/odo#615]
I'm trying to use odo  and i'm getting the above error message. 
Down grading networkx seems to be one suggest solution, but is proving to be a hassle? 
When will odo work with networkx 2.1? 
Or is there another cause/ fix. 

thanx

**Comment by groutr** [comment]
Odo will not work with NetworkX >=2.0.  To use the latest released version of odo, you need to downgrade to an earlier version of networkx (pre 2.0)

**Comment by soerendip** [comment]
Will this be fixed in future versions of odo?

**Comment by groutr** [comment]
@soerendip I'd use the latest 1.x version of networkx (1.11 I think).  I submitted a PR that fixes this, but I don't know who maintains this library.

**Comment by serpiko** [comment]
with networkx==1.9 it works, thanks for the solution
