### PR TITLE
Make odo compatible with NetworkX >=2.0

### LINKED ISSUE #615: AttributeError: 'DiGraph' object has no attribute 'edge'  - when trying to use odo
I'm trying to use odo  and i'm getting the above error message. 
Down grading networkx seems to be one suggest solution, but is proving to be a hassle? 
When will odo work with networkx 2.1? 
Or is there another cause/ fix. 

thanx

### PR DESCRIPTION
**Pull request by groutr**
NetworkX changed its API for accessing edges.  This PR makes odo compatible with NetworkX 1.0/2.0 by adding a compatibility function for each version of NetworkX.

Fixes #615

### CODE REVIEW

**Comment by soerendip** [comment]
Thanks for working on this.

**Comment by dhirschfeld** [comment]
It seems pretty clean and self-contained so I don't see any harm in merging it.

**Comment by bhipple** [comment]
Any chance we could get a new release with this?  When one is cut we can unwind some of the distribution patches for this in NixPkgs and simplify our packaging config, which is always nice!
